apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-px2o81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-px2o81
  namespace: my-nginx-px2o81
  labels:
    name: nginx-px2o81
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-px2o81
  template:
    metadata:
      namespace: my-nginx-px2o81
      labels:
        name: nginx-px2o81
    spec:
      containers:
      - name: nginx-px2o81
        image: nginx
        ports:
        - containerPort: 80

